version: '3.8'

services:
  app:
    build: .
    environment:
      - DSN=root:12345678@tcp(mysql:3306)/task_management?charset=utf8mb4&parseTime=True&loc=Local
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3004:3004"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: task_management
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=12345678"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s